In [3]:
import pandas as pd
import os

print("Pandas version:", pd.__version__)
print("Setup working!")

Pandas version: 2.3.3
Setup working!

In [4]:
# The project doc tells us core files use header=1 (row 0 is metadata, row 1 has column names)
companies = pd.read_excel('data/raw/companies.xlsx', header=1)

print("Shape:", companies.shape)          # (rows, columns)
print("\nColumn names:\n", companies.columns.tolist())
print("\nFirst 3 rows:")
companies.head(3)

Shape: (92, 12)

Column names:
 ['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

First 3 rows:

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64

In [1]:
import sys
print(sys.executable)

c:\Users\VISHNU\Downloads\nifty100_project\.venv\Scripts\python.exe

In [5]:
print("Missing values per column:")
print(companies.isnull().sum())

Missing values per column:
id                 0
company_logo       1
company_name       0
chart_link         0
about_company      0
website            1
nse_profile        1
bse_profile        1
face_value         1
book_value         1
roce_percentage    1
roe_percentage     2
dtype: int64

In [7]:
pl = pd.read_excel('data/raw/profitandloss.xlsx', header=1)

print("Shape:", pl.shape)
print("\nColumn names:", pl.columns.tolist())
print("\nUnique companies:", pl['company_id'].nunique())
print("\nYear range sample:", pl['year'].unique()[:10])
print("\nSample rows:")
pl.head(5)

Shape: (1276, 15)

Column names: ['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

Unique companies: 100

Year range sample: ['Dec 2012' 'Mar 2014' 'Mar 2015' 'Mar 2016' 'Mar 2017' 'Mar 2018'
 'Mar 2019' 'Mar 2020' 'Mar 2021' 'Mar 2022']

Sample rows:

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,1653,1451,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0
1,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0
2,63,ABB,Mar 2015,2289,1977,312.0,14.0,48,0,15,344,34.0,229,108.0,29.0
3,64,ABB,Mar 2016,2614,2250,365.0,14.0,50,3,14,398,36.0,255,120.0,29.0
4,65,ABB,Mar 2017,2903,2505,398.0,14.0,57,2,16,436,37.0,277,130.0,31.0

In [8]:
core_files = {
    'companies':      'data/raw/companies.xlsx',
    'profit_and_loss':'data/raw/profitandloss.xlsx',
    'balance_sheet':  'data/raw/balancesheet.xlsx',
    'cash_flow':      'data/raw/cashflow.xlsx',
    'analysis':       'data/raw/analysis.xlsx',
    'documents':      'data/raw/documents.xlsx',
    'prosandcons':    'data/raw/prosandcons.xlsx',
}

for name, path in core_files.items():
    df = pd.read_excel(path, header=1)
    print(f"{name:20s} → {df.shape[0]:>5} rows, {df.shape[1]:>2} columns")

companies            →    92 rows, 12 columns
profit_and_loss      →  1276 rows, 15 columns
balance_sheet        →  1312 rows, 13 columns
cash_flow            →  1187 rows,  7 columns
analysis             →    20 rows,  6 columns
documents            →  1585 rows,  4 columns
prosandcons          →    16 rows,  4 columns

In [9]:
pl_sample = pd.read_excel('data/raw/profitandloss.xlsx', header=1)

print("Year column — first 20 unique values:")
print(pl_sample['year'].unique()[:20])

Year column — first 20 unique values:
['Dec 2012' 'Mar 2014' 'Mar 2015' 'Mar 2016' 'Mar 2017' 'Mar 2018'
 'Mar 2019' 'Mar 2020' 'Mar 2021' 'Mar 2022' 'Mar 2023' 'Mar 2024' 'TTM'
 'Mar 2013' 'Dec 2013' 'Dec 2014' 'Dec 2015' 'Dec 2016' 'Dec 2017'
 'Dec 2018']